version: '3.3'
networks:
  my_network:
    driver: bridge

services:
  db:
    image: postgres:15
    networks:
      - my_network
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    networks:
      - my_network
    ports:
      - '6379:6379'

  api:
    build:
      context: .        # root folder
      dockerfile: api/Dockerfile
    networks:
      - my_network
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - my_network
    command: celery -A pipeline.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  pgdata:
