version: '3.3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A pipeline.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  pgdata:
