app: 
  name: data_pipeline
  environment: local

api:
  base_url: "https://jsonplaceholder.typicode.com"
  endpoints:
    posts: "/posts"

storage:
  database_url: "${DATABASE_URL}"   # Used env variable
  redis_url: "${REDIS_URL}"         # Used env variable
  s3_bucket: "${S3_BUCKET}"         # Used env variable

celery:
  broker_url: "${CELERY_BROKER_URL}"      # Used env variable
  result_backend: "${CELERY_RESULT_BACKEND}"  # Used env variable
